language: php
cache:
  bundler: true
  apt: true
  directories:
  - "$HOME/.composer/cache"
  - "$HOME/.drush/cache"
  - "$HOME/.npm"
  - "vendor"
php:
  - 5.5

sudo: false

addons:
  # Selenium tests are run against Firefox, so use the latest version.
  firefox: latest

mysql:
  database: drupal
  username: root
  encoding: utf8

before_install:
  - phpenv config-rm xdebug.ini
  - composer self-update
  - composer --version
  # Clear drush release history cache, to pick up new releases.
  - rm -f ~/.drush/cache/download/*---updates.drupal.org-release-history-*

install:
  # add composer's global bin directory to the path
  # see: https://github.com/drush-ops/drush#install---composer
  - export PATH="$HOME/.composer/vendor/bin:$PATH"

  # Install Drush
  - composer global require drush/drush:dev-master
  - phpenv rehash

  # MySQL Options
  - mysql -e 'SET GLOBAL wait_timeout = 5400;'
  - mysql -e "SHOW VARIABLES LIKE 'wait_timeout'"

  # PHP conf tweaks
  - echo 'max_execution_time = 120' >> drupal.php.ini;
  - echo 'sendmail_path = /bin/true' >> drupal.php.ini;
  - phpenv config-add drupal.php.ini
  - phpenv rehash

  # Build drupal + lightning from makefile
  - drush make --concurrency=5 build-lightning.make docroot -y
  # Rebuild dependencies from the makefile contained in the repo (not the one pulled from
  # drupal.org)
  - drush make -y --no-core drupal-org.make.yml docroot/profiles/lightning
  # Copy the install profile and Lightning-specific modules in the repo, since drupal.org
  # (which is used by drush make) is probably not as current.
  - cp -f lightning.* docroot/profiles/lightning
  - cp -R -f modules/lightning_features docroot/profiles/lightning/modules

  # Install lightning
  - cd docroot
  - drush si lightning --db-url=mysql://root:@localhost/drupal -y

before_script:
  - drush runserver --default-server=builtin 8080 &>/dev/null &
  - mv ../tests ./tests
  - cd tests
  - touch behat.local.yml
  - composer install
  # Download Selenium server.
  - wget -q http://goo.gl/PJUZfa -O selenium-server.jar
  # Initialize xvfb (see https://docs.travis-ci.com/user/gui-and-headless-browsers)
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  # Give xvfb time to start.
  - sleep 3
  # Start Selenium server in the background.
  - java -jar selenium-server.jar > /dev/null &
  - sleep 5

script:
  - bin/behat --strict
  - cd ../../modules/lightning_features/lightning_media/tests/js
  # TODO: The install step should go into before_script.
  - npm install > /dev/null
  - npm test

notifications:
  slack:
    secure: XEeN7K2vzyr3CfojGlRbgf8BEaqAoU6kKSGXi8/jTSw1VQ2zW7osTpCnxSBqvLCo+oXUQeA7p3u+w+84SAL1ReWaoY7y3lCf1MHlvIqWJeJOsgOvRlLulqT2bfAsfHhvXSX5C6TOSASs/OND6z6AXCQwX3V83e0eH497P1sprebk1Mcv5B7oAapuwSLo4dDrtIy2CgY2PtsPV1qgSY/eAUyJJ3yyu7P6nB+Ehj8En+dUHkS5lIIXNeAJLXY8H+oDQD1NIxek0mOeIvorh26CmbxY4Bt7j4FnexFKl5bCF/E361PWkQO1DkeE4YdbGGY9O4pZggyPjuGn1ijGSKknpcjir5iG4HcrfsMGjyai4568KJ+n1Jj8Mh8+PdCdWsU2x8hNdPGcxMf2DVV8qWlI3r1FzKPa3BbjPuk+304isDOahkzZJrkFF5rW1ngD1iZt2L20KbavD6TXYpXc9BMbCo2T85pXTfSlm9kw7p+LeNPTqcIPoplaOiRDfJQsGAD+WhXSpOS1P8BzUrlN8bjQmR2wlnyONAJDJm0vQTbx6Ox/BSrr+3zz4QatQOqX7HV7G5RuLGmtJOvTB/uAw34ETkUAbaAgkQYz14Rz2zXOX7E9P+FD4k+2WmK+WjLu/+P5uB0s+4a3L582nl9oZK7afZ2ZYIHxfaVAo/OXFAmfW6E=

matrix:
  fast_finish: true

